# Generated by Django 5.2.7 on 2026-03-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_payperiod_monthlysalary"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="backup_codes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Codes de secours pour la récupération de compte",
                verbose_name="Codes de secours",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_2fa_enabled",
            field=models.BooleanField(
                default=False,
                help_text="L'authentification à deux facteurs est-elle activée",
                verbose_name="2FA activé",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="totp_secret",
            field=models.CharField(
                blank=True,
                help_text="Secret pour l'authentification à deux facteurs",
                max_length=32,
                null=True,
                verbose_name="Secret TOTP",
            ),
        ),
    ]
