# Generated by Django 5.0.14 on 2026-03-22 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_user_backup_codes_user_is_2fa_enabled_and_more"),
        (
            "finance",
            "0002_alter_expense_options_alter_partnercontract_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CapitalTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INJECTION", "Injection de capital (Apport)"),
                            ("RETRAIT", "Retrait de capital"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Montant"
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date & Heure"
                    ),
                ),
                ("reason", models.CharField(max_length=255, verbose_name="Motif")),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Administrateur",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.currency",
                        verbose_name="Devise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction sur Capital",
                "verbose_name_plural": "Transactions sur Capital",
                "indexes": [
                    models.Index(fields=["type"], name="finance_cap_type_a8b5c9_idx"),
                    models.Index(
                        fields=["date_time"], name="finance_cap_date_ti_579cec_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProfitWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Montant retiré"
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date & Heure"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profit_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Administrateur",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.currency",
                        verbose_name="Devise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retrait de Bénéfice",
                "verbose_name_plural": "Retraits de Bénéfices",
                "indexes": [
                    models.Index(
                        fields=["date_time"], name="finance_pro_date_ti_520cc5_idx"
                    )
                ],
            },
        ),
    ]
