# Generated by Django 5.2.12 on 2026-03-14 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_user_backup_codes_user_is_2fa_enabled_and_more"),
        ("operations", "0003_caisse_operations__agent_i_9eb1d4_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feegrid",
            name="currency",
            field=models.ForeignKey(
                limit_choices_to={"code": "USD"},
                on_delete=django.db.models.deletion.CASCADE,
                to="core.currency",
                verbose_name="Devise (toujours USD)",
            ),
        ),
        migrations.AlterField(
            model_name="feegrid",
            name="fee_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="Frais Fixe (USD)"
            ),
        ),
        migrations.AlterField(
            model_name="feegrid",
            name="max_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="Montant Max (USD)"
            ),
        ),
        migrations.AlterField(
            model_name="feegrid",
            name="min_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="Montant Min (USD)"
            ),
        ),
        migrations.AddConstraint(
            model_name="feegrid",
            constraint=models.UniqueConstraint(
                fields=("min_amount", "max_amount"), name="unique_fee_range"
            ),
        ),
    ]
