# Generated by Django 5.0.14 on 2026-03-22 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_user_backup_codes_user_is_2fa_enabled_and_more"),
        ("operations", "0004_alter_feegrid_currency_alter_feegrid_fee_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FondAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Montant"
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date & Heure"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Exemple : Fonds de démarrage Lundi",
                        verbose_name="Note",
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations_donnees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Administrateur",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        limit_choices_to={"role": "AGENT"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations_recues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.currency",
                        verbose_name="Devise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allocation de fonds (Agent)",
                "verbose_name_plural": "Allocations de fonds (Agents)",
                "indexes": [
                    models.Index(
                        fields=["agent"], name="operations__agent_i_dc80e3_idx"
                    ),
                    models.Index(
                        fields=["date_time"], name="operations__date_ti_1d3a29_idx"
                    ),
                ],
            },
        ),
    ]
